In [1]:
#202101491 신서연

In [2]:
#NNLab
#86p 예제
import numpy as np

activation_function=lambda x: 1/(1 + np.exp(-x))
input=np.array([0.9,0.1,0.8],ndmin=2).T
print("input.T\n",input)

#88p 가중치
Winput_output=np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_output\n",Winput_output)

Xoutput=np.dot(Winput_output,input)
print("Xoutput\n",Xoutput)

output=activation_function(Xoutput)
print("output\n",output)

input.T
 [[0.9]
 [0.1]
 [0.8]]
Winput_output
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Xoutput
 [[1.16]
 [0.42]
 [0.62]]
output
 [[0.76133271]
 [0.60348325]
 [0.65021855]]


In [5]:
i_w3=np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
h_w3=np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
target = [[0.01],[0.01],[0.99]]
o_e3=target#-o_o3
h_e3=backward(o_e3,h_w3)
h_e3
h_nw3=WeightUpdate(o_e3,h_w3,h_o3)
h_nw3

NameError: name 'backward' is not defined